---
# tasks file for ansible-recap

- name: Fail if not RedHat OS family
  fail:
    msg: "Recap packages are only available in EPEL for the RedHat OS Family"
  when: ansible_os_family|lower != "redhat"

- name: Install required packages
  action: >
    {{ ansible_pkg_mgr }} name={{ item }} state=latest update_cache=yes
  with_items: recap
  when: ansible_os_family|lower == "redhat"

- name: Enable recap features
  ini_file:
    path: /etc/recap
    section: null
    option: "{{ item[0] }}"
    value: "{{ item[1] }}"
    backup: yes
    no_extra_spaces: yes
  with_nested:
    - [ 'USESAR', 'yes' ]
    - [ 'USESARR', 'yes' ]
    - [ 'USESARQ', 'yes' ]
    - [ 'USENETSTATSUM', 'yes' ]
    - [ 'USEDF', 'yes' ]
    - [ 'USESLAB', 'yes' ]
    - [ 'USEFDISK', 'yes' ]

- name: Run recap once
  command: recap

#- name: Schedule additional recaps in cron


